### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blalyasar**
Readme update for rpm based Linux

### CODE REVIEW

**Comment by noyanc** [comment]
@blalyasar Can not we install all libraries in just 1 command? Such as:
`sudo dnf install glm-devel glfw glfw-decel glew-devel freetype-devel freetype assimp assimp-devel`

**Comment by noyanc** [comment]
Another thing; is "glfw-decel" or "glfw-devel"?

**Comment by noyanc** [comment]
@blalyasar A third thing is; shouldn't we add "git cmake g++-7" libs into the install command as well?

**Comment by blalyasar** [comment]
Maybe .    you know more than me :)

**Pull request merged**
